Service : auth


Releases:
  -
    Version: 1.0.0
    Path: ./swagger1_0_0.yaml
    Tag: development
  -
    Version: 0.0.1
    Path: ./swagger0_0_1.yaml
    Tag: Production
  -
    Version: 0.0.2
    Path: ./swagger0_0_2.yaml
    Tag: InternalRelease

